### PR TITLE
better flake inputs + overhaul dependency management

### PR DESCRIPTION
**Pull request by getchoo**
~~updated flake inputs~~ matched our flake inputs with nixified-ai's. this allows for our builds to reproduce the same dependencies, which in turn saves on disk space for those who use this *and* nixified-ai projects, as well as prevents us from building what is basically the same thing twice.

the way we manage dependencies has also been changed: instead of overriding them all in the osmosis derivation, an overlay is applied with nixified-ai's packages. this lets us easily integrate our packages with theirs, along with making future overrides both easier and more consistent

### CODE REVIEW

**Comment by AshtakaOOf** [comment]
So many Pull Requests today...

**Comment by ryanccn** [comment]
@getchoo CI failed 🥺

**Comment by getchoo** [comment]
seems to be tiffile's pytest suite ooming the runner again. i'll try adding swap to it, and if that doesn't work i'll just do nix magic to disable tests for it completely during builds

**Comment by getchoo** [comment]
im going to drop a few things from here...probably should've just made a new pr now that i think about it :/

**Pull request closed without merging**
